//LOCALHOST
###
# Root
GET http://localhost:8080/ HTTP/1.1
###
# Read API Documentation
GET http://localhost:8080/api-docs/ HTTP/1.1
###
# Get all contacts
GET http://localhost:8080/contacts HTTP/1.1
###
# Get a single contact
GET http://localhost:8080/contacts/<id> HTTP/1.1
###
# Create a new Contact
POST http://localhost:8080/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Joe",
    "lastName": "Schmoe",
    "email": "j.schmoe@email.com",
    "favColor": "Blue",
    "birthday": "1985-11-09"
}
###
# Update a Contact
PUT http://localhost:8080/contacts/<id> HTTP/1.1
Content-Type: application/json

{
    "favColor": "Green"
}
###
# Delete a Contact
DELETE http://localhost:8080/contacts/<id> HTTP/1.1

//RENDER
###
# Root
GET https://w01-starter-service.onrender.com/ HTTP/1.1
###
# Read API Documentation
GET https://w01-starter-service.onrender.com/api-docs/ HTTP/1.1
###
# Get all contacts
GET https://w01-starter-service.onrender.com/contacts HTTP/1.1
###
# Get a single contact
GET https://w01-starter-service.onrender.com/contacts/<id> HTTP/1.1
###
# Create a contact
POST https://w01-starter-service.onrender.com/contacts HTTP/1.1
Content-Type: application/json

{
    "firstName": "Joe",
    "lastName": "Schmoe",
    "email": "j.schmoe@email.com",
    "favColor": "Blue",
    "birthday": "1985-11-09"
}
###
# Update a Contact
PUT https://w01-starter-service.onrender.com/contacts/<id> HTTP/1.1
Content-Type: application/json

{
    "favColor": "Green"
}
###
# Delete a Contact
DELETE https://w01-starter-service.onrender.com/contacts/<id> HTTP/1.1
